service: patient-matching-api

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30
  memorySize: 1024
  environment:
    USE_DOCUDB: true
    DOCUDB_CONNECTION_STRING: ${env:DOCUDB_CONNECTION_STRING}
    DOCUDB_DATABASE: ${env:DOCUDB_DATABASE, 'patient_db'}
    DOCUDB_COLLECTION: ${env:DOCUDB_COLLECTION, 'patients'}

functions:
  api:
    handler: main.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true